# Generated by Django 3.1.1 on 2020-09-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('custId', models.AutoField(primary_key=True, serialize=False)),
                ('custName', models.CharField(max_length=50)),
                ('custEmailId', models.CharField(max_length=50, unique=True)),
                ('custPassword', models.CharField(max_length=50)),
                ('custContact', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
