# Generated by Django 3.1.1 on 2020-09-19 10:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('roomId', models.AutoField(primary_key=True, serialize=False)),
                ('roomType', models.CharField(choices=[('Standard', 'Standard'), ('Deluxe', 'Deluxe'), ('Luxury', 'Luxury')], max_length=30)),
                ('beds', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('quest', models.IntegerField()),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.roommodel')),
            ],
        ),
    ]
