# Generated by Django 3.1.1 on 2020-09-19 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0003_adminmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingModel',
        ),
    ]
