# Generated by Django 3.1.1 on 2020-09-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0004_delete_bookingmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('quest', models.IntegerField()),
                ('roomId', models.IntegerField()),
                ('roomType', models.CharField(max_length=30)),
                ('beds', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
            ],
        ),
    ]
