# Generated by Django 3.1.1 on 2020-09-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0008_auto_20200919_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='roommodel',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
